### PR TITLE
Ensure import for ToFloat and Remainder.

### PR DESCRIPTION
**Pull request by pgfm1**
Discussion in Discord explored that `toFloat64(Int32)` did not appear to be working properly. Found that although `ToFloat32`, `ToFloat64`, and `Remainder` were implemented in Pervasive, they were not recognized in applications. Verified other parts of the compiler pipeline (e.g. all source copied properly, included in build) and also verified that a test application using `toFloat64(Int32)` worked properly after applying this change.

If I get some time later and this isn't merged, I can look into adding tests that use all of this functionality, but figured I'd open this PR at least for documentation.

The original error was `I can't find a callable named toFloat64.` (`TypeErrors.ml` line `343`).

### CODE REVIEW

**Comment by AlbertoGP** [comment]
> If I get some time later and this isn't merged, I can look into adding tests that use all of this functionality, but figured I'd open this PR at least for documentation.

I’ve added some trivial tests from `001-trivial/011-integer-conversions/` as `001-trivial/015-float-conversions/` that do catch the original error: https://github.com/pgfm1/austral/pull/1
```
AUSTRAL STDERR
	{
	  "module": "Test",
	  "kind": "Generic Error",
	  "text": [
	    { "type": "text", "content": "I can't find a " },
	    { "type": "text", "content": "callable" },
	    { "type": "text", "content": " named " },
	    { "type": "code", "content": "toFloat32" },
	    { "type": "text", "content": "." }
	  ],
	  "span": null,
	  "context": null
	}
```
If you merge that pull request into your branch (you can select merge, or squash, or rebase before clicking the green button) these tests will be added to your pull request.

**Comment by pgfm1** [comment]
Thank you! I'll review/update when I get free (4 hours or so)

**Comment by pgfm1** [comment]
Annnnnnnd the tests are merged into this branch and available in this PR!

**Review by eudoxia0 — APPROVED** [review]

**Comment by eudoxia0** [comment]
Thanks for fixing!

**Pull request merged**
