### PR TITLE
Add swap intrinsic

### PR DESCRIPTION
**Pull request by qbradley**
I did not find an existing way to update a field of a record. If there is a better way to accomplish this let me know. Regarding the safety of this function, I was not certain, but I imagined that as long as a record does not contain borrowed references then this intrinsic would not introduce bugs. Swapping writeable references should not change the required consumption/use of any linear variables. I found this swap intrinsic necessary to implement rehash in my hashtable when passed a mutable reference to the hashtable. Internally the hashtable uses a Buffer[IndexEntry] and I need to replace it with a new one in the rehash case.

### CODE REVIEW

**Comment by eudoxia0** [comment]
Hmm hold on can't you do:

```
let old: T := !ref2;
ref1 := old;
ref2 := !ref1;
```

**Comment by qbradley** [comment]
An example of what does not work:

```
record Example[T]: Type is
    items: Buffer[T];
end;

generic[R: Region]
function update(example: &![Example, R], new_items: Buffer[T]): Unit is
    let old: Buffer[T] := !example->items;
    example->items := new_items;
    destroyFree(old);
end;
```

But with the proposed change, this works:

```
    swap(example->items, &!new_items);
    destroyFree(new_items);
```

**Comment by eudoxia0** [comment]
Yes, you're right. You can't use it as an lvalue because it's not `Free`. I've seen a `swap` intrinsic in various linear-ish type systems so this is probably the way to go. Let me review.

**Comment by eudoxia0** [comment]
So I think this is necessary, but I think I'm going to try implementing this with intrinsics. I don't want to touch the `prelude.c` code unnecessarily (I think we can do this largely without C).

**Review by eudoxia0 — APPROVED** [review]

**Comment by eudoxia0** [comment]
So sorry for the delay. I'm going to merge this now, but I'll probably replace the code in the runtime for an intrinsic call (I get anxious at loops manipulating byte buffers)

**Pull request merged**
