### PR TITLE
Use generics in trapping arithmetic

### PR DESCRIPTION
**Pull request by jacereda**
This might seem slow, but the C compiler seems to do a great job (at least with `-O2 -flto`).

I faced a bug with the generics, if instead of `let result: T := lhs;` I use `let result: T := 0;` the result ends up being emitted as an `int32_t` instead of the proper type.

### CODE REVIEW

**Comment by jacereda** [comment]
Oh, this builds on top of #326

**Comment by eudoxia0** [comment]
Thanks!

I think long-term I'm going to have to make `abort` generic (take some sort of typeclass-based string-reader interface) so error messages can be constructed more easily.

**Comment by jacereda** [comment]
I don't know how I did the benchmarking here, but looks like I was wrong.  Looks like it isn't postponing the string creation until it's needed and a fib benchmark ends up taking twice as long.

If there was some way to get the name of a type (so that the generic functions don't need to receive a string) it would be great. Are there plans to support that?

**Comment by eudoxia0** [comment]
Maybe. But you can't compose `FixedArray` values (because returning stack-allocated arrays would return a point to invalid memory). I can roll back the changes.

**Pull request merged**
