### PR TITLE
Make sizeof return ByteSize instead of Index

### PR DESCRIPTION
**Pull request by jacereda**

### CODE REVIEW

**Comment by eudoxia0** [comment]
This all looks quite reasonable. However I think I need to first add a test that integer conversions work from every type to every other type. As I recall the integer conversion code requires touching the prelude.

**Comment by eudoxia0** [comment]
(Also, it might be good to move integer conversions into the Prelude via typeclasses named like `ToNat8` etc., since the current system is not ideal).

**Comment by jacereda** [comment]
Right, I noticed that something like this fails due to the lack of Index->xxx functions:

```
   for i from 0 to 10:
       print(i : Nat8);
```

**Comment by jacereda** [comment]
Perhaps using Int64 and Nat64 as intermediate formats would avoid the explosion of conversion functions. That is:

Int16->Int8 would be Int16->Int64->Int8

Int16->Nat8 would be Int16->Int64->Nat64->Nat8

That looks convoluted, but I suspect the C compiler can do a good job with that.

**Comment by eudoxia0** [comment]
I think something like this:

```
typeclass ToNat8(T: Type) is
    method toNat8(value: T): Option[Nat8]; -- None represents non-representability.
end;

instance ToNat8(Nat8);
...
instance ToNat8(Index);
```

Repeated for every integer type might be acceptable. It makes for an explosion of conversion functions, but the current system (where a Python script autogenerates a slew of ad-hoc conversion functions which are embedded in the prelude) is not great.

In terms of ergonomics there's little difference between `toInt64(x)` and `x : Int64`.

Additionally, one of Austral's anti-features is "no implicit function calls". The type conversion operator is close to an implicit function call. And it's very overloaded, since it serves to simultaneously.

1. Clarify the return type of return-type polymorphic functions.
2. Cast integer literals to their appropriate type.
3. Convert across integer types at runtime.
4. Degrading read references into write references.

**Comment by eudoxia0** [comment]
Maybe not a function just for that but there should be an equivalent of `unwrap` that aborts in the `None` case.

**Comment by jacereda** [comment]
Sounds good.

**Comment by eudoxia0** [comment]
Thanks!

**Pull request merged**
