### PR TITLE
VSCode Syntax Highlighting for Austral

### PR DESCRIPTION
**Pull request by ishehadeh**
The TextMate syntax is a bit of a disaster, but it gives pretty-decent context-aware syntax highlighting. I'll look into generating more of it, or at least using a format other than JSON in future revisions.

### CODE REVIEW

**Comment by eudoxia0** [comment]
Thanks for contributing! I can tell this was a lot of work. Let me try it out locally.

**Comment by eudoxia0** [comment]
@ishehadeh do you want me to review this now and possible merge, or do you want to add more commits? I'm happy to review further PRs (which would probably be easier than reviewing one big PR).

**Comment by ishehadeh** [comment]
It'd be great if you could review this now. It's a little rough, but its complete enough I can hold any fixes for a future PR. Sorry about the ~100 commit dump, I got a little carried away haha.

**Comment by eudoxia0** [comment]
Can you add brief instructions on how to load this extension? Since it's not on the marketplace and there's no VSIX file I'm not sure how to load this into VSCode to test it.

**Comment by ishehadeh** [comment]
Yep! added some basic install/debug extension. The quickest way to do it is to open the extension folder in vscode and start debugging. The debug profile will open a new vscode instance with the extension loaded.

**Comment by eudoxia0** [comment]
This works great! Thank you for taking the time to do this.

**Review by eudoxia0 — APPROVED** [review]

**Pull request merged**
